### ISSUE TITLE
ZeroTermux in split screen mode, the keypad flashes continuously

### ISSUE THREAD

**Issue by DreamOneTop** [hanxinhao000/ZeroTermux#1]
Device: Huawei Mate 20 Dual SIM TD-LTE (China)
System: EMUI 11.0.0 (Android 10)
No ROOT
From AIDA64 
As you can see, the keypad keeps blinking

https://user-images.githubusercontent.com/83908457/123517314-dc27bc80-d6d2-11eb-8af3-cde91079537a.mp4

**Comment by hanxinhao000** [comment]
Your question has been accepted, but I don’t have any equipment to test,

**Comment by hanxinhao000** [comment]
My device: OnePlus 5T, the father of Android PH1

**Comment by DreamOneX** [comment]
After my updated ZeroTermux0.116.06, the question was solved.Thanks
