### ISSUE TITLE
更新x86_alpine

### ISSUE THREAD

**Issue by poisongod** [hanxinhao000/ZeroTermux#10]
Vshell与Alpine Term是一个类termux搭建的qemu虚拟机，支持串口终端输出，vnc输出，如果您会写apk程序，也可以把更多的display选项打包进去，下载地址在下面，当然这对于China的朋友应该需要科学上网才能够访问
[Vshell](https://github.com/BryleHelll/android-vshell) 
[Alpine Term v16.0](https://archive.org/details/alpine-term-v16.0) 
[Alpine Term v14.0 可以在这里下载其他虚拟磁盘开发者提供了三个可用的系统
AlpineLinux
ArchLinux
DebianLinux](https://archive.org/details/alpine-term-v14.0)

**Comment by hanxinhao000** [comment]
这个对于目前的ZeroTermux 如果整合会使体积增大，目前已经有很多人反馈体积过大，目前整个ZT用户具体使用次数我们并不清楚，但是为了不让体积增大，目前我们是不会整合此发行版本的
