### ISSUE TITLE
add video background feature

### ISSUE THREAD

**Issue by kazuyagodsz** [hanxinhao000/ZeroTermux#22]
hello dev I'm very happy with zerotermux, I have a request for you to add a video background and keyboard feature like the old utermux, and add a float feature on zerotermux, and my last request make a decoder feature to make the program easier, maybe this is very difficult for you but if it is realized I am very happy, thank you for the developer who has made zerotermux as beautiful as this

**Comment by hanxinhao000** [comment]
解码器功能能具体说一下吗
