### ISSUE TITLE
CANNOT LINK EXECUTABLE "curl": cannot locate symbol "nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation" referenced by "/data/data/com.termux/files/usr/lib/libcurl.so"

### ISSUE THREAD

**Issue by ywszdxx** [hanxinhao000/ZeroTermux#30]
~ $ curl
CANNOT LINK EXECUTABLE "curl": cannot locate symbol "nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation" referenced by "/data/data/com.termux/files/usr/lib/libcurl.so"
...
~ $
![Screenshot_20230304_172629_com termux](https://user-images.githubusercontent.com/107831384/222890487-e88c03c4-06ba-4f9e-946d-46605a052550.jpg)

**Comment by ywszdxx** [comment]
@hanxinhao000

**Comment by hanxinhao000** [comment]
pkg upgrade && pkg install curl openssl -y

**Comment by hanxinhao000** [comment]
pkg upgrade && pkg reinstall curl openssl -y
