### ISSUE TITLE
Screenshot problem

### ISSUE THREAD

**Issue by Mahantor** [hanxinhao000/ZeroTermux#31]
When I want to use the gesture of dragging three fingers on the screen to take a screenshot, the AARCH64 toolbox menu opens.
Please solve this problem

**Comment by hanxinhao000** [comment]
This problem is currently being considered for a solution, and it should be fixed in the next few versions

**Comment by hanxinhao000** [comment]
已修复这个问题：https://github.com/hanxinhao000/ZeroTermux/commit/9d5b5169cec1af33dda0140f897a167bc0b59cb4
