### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by ysq1212** [hanxinhao000/ZeroTermux#32]
安卓6是不是用不了

**Comment by hanxinhao000** [comment]
项目目前最低版本支持

## Project-wide Gradle settings.
#
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx10248m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048M
android.useAndroidX=true

**minSdkVersion=23**  Android6.0
targetSdkVersion=28
ndkVersion=22.1.7171670
compileSdkVersion=33

markwonVersion=4.6.2

android.enableJetifier=true

如果你想要在低版本运行请，更改主APP 的 minSdkVersion 与lib的 minSdkVersion，可能会遇到很多问题

**Comment by hanxinhao000** [comment]
ZeroTermux是同步支持了termux版本，如果降低版本可能会出现其他问题
