### ISSUE TITLE
zerotermux 怎样使用系统API (Termux:API)

### ISSUE THREAD

**Issue by linxi-520** [hanxinhao000/ZeroTermux#34]
Termux:API和zerotermux不相容,安装ZeroTermux后无法安装Termux:API

**Comment by hanxinhao000** [comment]
ZT 左侧栏有，安装一下即可

**Comment by hanxinhao000** [comment]
或者安装这个APK：https://github.com/hanxinhao000/ZeroTermux/blob/main/app/src/main/assets/apk/termux_api.ip
.ip 更改成 .apk

**Comment by LinxiDev** [comment]
好的感谢大佬
