### ISSUE TITLE
安卓6安装后启动黑屏无法进入主页面

### ISSUE THREAD

**Issue by mlabalabala** [hanxinhao000/ZeroTermux#35]

**Comment by hanxinhao000** [comment]
能提供下机型不

**Comment by mlabalabala** [comment]
比较冷门的乐视手机  Le X620 安卓6.0

**Comment by mlabalabala** [comment]
还有华为荣耀平板 JDN-W09，也是安卓6，有一样的问题

**Comment by hanxinhao000** [comment]
我这边没有Android 6.0 的机型，没法测试，模拟器上你试了没

**Comment by mlabalabala** [comment]
![image](https://user-images.githubusercontent.com/91363385/236451835-727b951a-fbc4-4048-8c50-bc63cc756384.png)
用这个mumu模拟器 安卓6，也是打开进不去

**Comment by csxy999** [comment]
我也是打开黑屏，侧边栏能划出，点击空白处可以弹出输入法但是没有命令输入的界面

**Comment by Chenamel** [comment]
我的乐视2（lex620）也是这样，打开后是深灰色界面，没有键盘等控件

**Comment by hanxinhao000** [comment]
ZeroTermux不支持8.0以下Android操作系统
