### ISSUE TITLE
你好，图片中的这个问题要怎么搞？手机恢复出厂设置了还是不行

### ISSUE THREAD

**Issue by liugdls** [hanxinhao000/ZeroTermux#38]
![image](https://github.com/hanxinhao000/ZeroTermux/assets/50070611/e010ea4a-3212-4520-a701-0b2e236c82b0)

**Comment by SharpIceX** [comment]
这个是设备问题来着
@2096779623

**Comment by liugdls** [comment]
折腾了好多次 最终是软件安装后不要打开，重启手机再打开就好了，但是接着部署了青龙面板的恢复包，青龙面板是无法正常登录的，一直报错，估计还是安卓高版本系统的问题。
