### ISSUE TITLE
卸载zero后无法安装官方的termux

### ISSUE THREAD

**Issue by summer-breeze123** [hanxinhao000/ZeroTermux#42]
卸载ZeroTermux后试图安装F-droid内的termux，提示如下信息
```
STDERR Failure 
[INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: 
Reconciliation failed...: 
Reconcile failed: Package com.termux has no signatures that match those in shared user com.termux; ignoring!]
 错误识别码：1
```
根据termux项目的issues里的报告，是因为没有卸载掉所有的插件，api，x11等。
我确认已经卸载从ZeroTermux下载的所有插件，但依然没有效果，甚至在安装官方提供的插件是，依然提示上述信息。

**Comment by SharpIceX** [comment]
请提供一份应用程序列表

**Comment by summerBreeze03** [comment]
> 请提供一份应用程序列表

[list.txt](https://wwfx.lanzouw.com/iIznC167srgb)

**Comment by SharpIceX** [comment]
> > 请提供一份应用程序列表
> 
> [list.txt](https://wwfx.lanzouw.com/iIznC167srgb)

请卸载
质感文件，对应包名：me.zhanghai.android.files

**Comment by hanxinhao000** [comment]
在ZeroTermux工具箱当中有一键卸载功能，请点击卸载完成之后，再主动卸载ZeroTermux
