### ISSUE TITLE
安卓5無法安裝

### ISSUE THREAD

**Issue by zackzheng1121** [hanxinhao000/ZeroTermux#43]
想將安卓5的電視盒子改為伺服器，但是安裝時顯示剖析套件時出現問題，請問我可以怎麼做?

**Comment by SharpIceX** [comment]
很抱歉，Termux最低也需要安卓7，這並不是ZeroTermux的問題。

**Comment by zackzheng1121** [comment]
好的

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
乾淨無病毒。www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

SharpIce 锐冰龙 ***@***.***> 於 2023年8月23日 週三 下午3:45寫道：
