### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by PILIHU2022** [hanxinhao000/ZeroTermux#44]
- OS：Android11
安装了zerotermuxcoremanager后还是无法安装zerotermux
就像下图
![Screenshot_20230830-221152](https://github.com/hanxinhao000/ZeroTermux/assets/100511118/dedf46c3-6106-403c-892a-7d8395ebbdba)

**Comment by hanxinhao000** [comment]
请卸载干净之前的termux以及termux插件，
