### ISSUE TITLE
无法安装proot容器

### ISSUE THREAD

**Issue by Sylphinford** [hanxinhao000/ZeroTermux#46]
选择linux版本后安装报错了
日志里有
检测到您无权读取/proc/buddyinfo,修复中...
Fixing /proc/buddyinfo...
这类报错

[termux-report_issue_from_transcript.log](https://github.com/hanxinhao000/ZeroTermux/files/13169940/termux-report_issue_from_transcript.log)

[termux-report_issue_from_transcript.log](https://github.com/hanxinhao000/ZeroTermux/files/13196477/termux-report_issue_from_transcript.log)

**Comment by SharpIceX** [comment]
proot无法读取/proc是正常的，而且这个并非Termux及衍生版本的问题，这是tmoe的问题，但是tmoe已经停止更新。
