### ISSUE TITLE
Termux:API 没有权限：'SYSTEM_ALERT_WINDOW'

### ISSUE THREAD

**Issue by sysdefault** [hanxinhao000/ZeroTermux#48]
![IMG_20231203_115935](https://github.com/hanxinhao000/ZeroTermux/assets/72608492/1ceef95f-98cf-4a78-8bea-fe22b62a02e3)

安卓版本：12
MIUI: 13.0.7

termux-api 带的 termux-toast, 用来显示临时窗口通知，在 ZeroTermux 界面可以正常显示，切换到桌面或其他应用无法显示，需要显示在其他应用上层权限SYSTEM_ALERT_WINDOW，看了AndroidManifest.xml里面没有写这个权限，在设置的这两个地方也没有开关
![IMG_20231203_142319](https://github.com/hanxinhao000/ZeroTermux/assets/72608492/306578dd-70b4-4206-a22b-8178786d0c7f)
![IMG_20231203_114930](https://github.com/hanxinhao000/ZeroTermux/assets/72608492/53b39736-5ffe-4aec-acb0-1a0ddcb7469f)

我尝试手动添加这个权限到AndroidManifest.xml并重新签名apk，但是签名不同安装不上，卸载原来的Termux:API也无法安装，应该是与Zerotermux冲突了

**Comment by sysdefault** [comment]
交互对话框部件 termux-dialog 同理也是如此

**Comment by SharpIceX** [comment]
稍等一下我进行测试看看

**Comment by SharpIceX** [comment]
我Termux和ZeroTermux测试了一下没有出现问题诶。。

**Comment by sysdefault** [comment]
> 我Termux和ZeroTermux测试了一下没有出现问题诶。。

是不是是MIUI的原因，~~后台弹出界面权限 就是MIUI系统自行添加的权限。作用就是限制应用在后台弹出界面的权利，默认关闭，需手动赋予该权限应用才能在后台拉起Activity等界面~~。Termux:API应用设置界面没有显示悬浮窗权限开关选项。

**Comment by SharpIceX** [comment]
> > 我Termux和ZeroTermux测试了一下没有出现问题诶。。
> 
> 不是是MIUI的原因，后台弹出界面权限就是MIUI系统自行添加的权限。就是限制应用在后台弹出界面的权限，默认关闭，需要手动赋予该权限应用才能在后台拉起活动等界面。 :API应用设置界面没有这个开关

不清楚，我两次测试都是MIUI

**Comment by sysdefault** [comment]
> > > 我Termux和ZeroTermux测试了一下没有出现问题诶。。
> > 
> > 
> > 不是是MIUI的原因，后台弹出界面权限就是MIUI系统自行添加的权限。就是限制应用在后台弹出界面的权限，默认关闭，需要手动赋予该权限应用才能在后台拉起活动等界面。 :API应用设置界面没有这个开关
> 
> 不清楚，我两次测试都是MIUI

您那边再测试一下?我用这个脚本测试，刚切换离开zerotermux界面时，前几次输出都能显示，过一会循环到中间那几次就不显示了，想要再显示的话，重新切换回zerotermux，但是已经是从中间那几次后面的次数显示了。
也就是说，当长期在后台运行时，这个显示功能几乎不可用。

如演示视频，切换到后台以后过了一会，第6 7次已经不能显示了，再次回到zerotermux恢复了但已经是第8次，中间那几次就没显示

https://github.com/hanxinhao000/ZeroTermux/assets/72608492/88afdc7c-0b5b-47b7-8b59-a1a07fea1071


#!/bin/bash

for i in {1..10}; do
  termux-toast -s -b white -c black -g top 第$i次输出
  sleep 3
done

**Comment by sysdefault** [comment]
或者您那边把添加这个权限SYSTEM_ALERT_WINDOW的Termux:API.apk发我测试一下？让该应用设置里有这个~~后台弹出界面权限~~显示悬浮窗权限，我再打开它测试?
因为我自己打包签名的安装不上😂

**Comment by SharpIceX** [comment]
> 或者您那边把添加这个权限SYSTEM_ALERT_WINDOW的Termux:API.apk发我测试一下？让该应用设置里有这个后台弹出界面权限，我再打开它测试? 因为我自己打包签名的安装不上😂

我没有修改Termux API，我这边后台是可以持续输出的

**Comment by sysdefault** [comment]
气人🤗🤗你是MIUI几？我这13就是这个样子切到后台就不行了，这个应用的设置里也没那个~~后台弹出界面权限开关~~，zerotermux的设置里就有，前面说错了是显示悬浮窗权限

**Comment by SharpIceX** [comment]
> 气人🤗🤗你是MIUI几？我这13就是这个样子切到后台就不行了，这个应用的设置里也没有那个后台弹出界面权限开关，zerotermux的设置里有

我是MIUI12.5.9

**Comment by sysdefault** [comment]
应该不是权限的问题，可能跟应用后台存留有关，电池优化还有唤醒锁都搞了仍然不行，唉
