### ISSUE TITLE
手机已经root，安装了centos，启动的时候提示没有安装树莓派和proot

### ISSUE THREAD

**Issue by wu529778790** [hanxinhao000/ZeroTermux#5]
安装完proot之后，centos可以启动，启动之后，安装宝塔面板，宝塔面板提示没有权限创建www文件夹

**Comment by 2096779623** [comment]
图

**Comment by SharpIceX** [comment]
> 安装之后，centos可以启动，启动之后，安装宝塔面板，宝塔面板提示没有权限创建wwwproot之后的文件夹

无root请务必使用Proot+Qemu(amd64)
有Root直接使用Chroot容器
