### ISSUE TITLE
A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)

### ISSUE THREAD

**Issue by skynacu** [hanxinhao000/ZeroTermux#50]
NodeError [SystemError]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)
1|panel    | 2024-01-16T21:32:44:     at Object.networkInterfaces (node:os:259:16)
1|panel    | 2024-01-16T21:32:44:     at Object.<anonymous> (/ql/node_modules/.pnpm/nodemailer@6.7.3/node_modules/nodemailer/lib/shared/index.js:15:66)
1|panel    | 2024-01-16T21:32:44:     at Module._compile (node:internal/modules/cjs/loader:1103:14)
1|panel    | 2024-01-16T21:32:44:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
1|panel    | 2024-01-16T21:32:44:     at Module.load (node:internal/modules/cjs/loader:981:32)
1|panel    | 2024-01-16T21:32:44:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
1|panel    | 2024-01-16T21:32:44:     at Module.require (node:internal/modules/cjs/loader:1005:19)
1|panel    | 2024-01-16T21:32:44:     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
1|panel    | 2024-01-16T21:32:44:     at require (node:internal/modules/cjs/helpers:102:18)
1|panel    | 2024-01-16T21:32:44:     at Object.<anonymous> (/ql/node_modules/.pnpm/nodemailer@6.7.3/node_modules/nodemailer/lib/mailer/index.js:4:16) {
1|panel    | 2024-01-16T21:32:44:   code: 'ERR_SYSTEM_ERROR',

**Comment by SharpIceX** [comment]
This should be a problem with Android and not with ZeroTermux and Termux.
https://github.com/termux/termux-app/issues/3497

**Comment by skynacu** [comment]
ok，thanks a lot
