### ISSUE TITLE
zerotermux被系统杀后台问题

### ISSUE THREAD

**Issue by 2861164410** [hanxinhao000/ZeroTermux#51]
更新了安卓14系统，频繁被杀后台，脚本几小时杀一次，希望添加无障碍保活或者其他保活方法
版本:0.118.38.1

**Comment by Neko520nya** [comment]
已经给后台应用上锁，关闭电池优化，且各种方法尝试无效

**Comment by SharpIceX** [comment]
这并非ZeroTermux和Termux的问题，因为定制OEM的系统的原因基本上都会被杀掉，除非改用AOSP。
