### ISSUE TITLE
App not installed error

### ISSUE THREAD

**Issue by TechMorgan** [hanxinhao000/ZeroTermux#52]
I get this error while installing it:

App has requested an already existing shared user, but their signatures don't match

Full error:
INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Reconciliation failed...: Reconcile failed: Package com.termux has no signatures that match those in shared user com.termux; ignoring!

**Comment by SharpIceX** [comment]
Hello!  If you want to use ZeroTermux, you should uninstall all Termux-related applications, such as Termux-API

**Comment by TechMorgan** [comment]
> Hello! If you want to use ZeroTermux, you should uninstall all Termux-related applications, such as Termux-API

Yeah it works now
