### ISSUE TITLE
安卓14下若不开启vpn，存在无法联网的问题

### ISSUE THREAD

**Issue by 1171800312** [hanxinhao000/ZeroTermux#55]
建立网络链接时会报权限不够，疑似原因是安卓14对非明文传输的网络连接进行了限制。望修复此问题

**Comment by fish4terrisa-MSDSM** [comment]
也许你可以向上游termux反映一下？你可以先试试最新的termux有没有这个问题（你可以用zerotermux的签名自己打包一个apk）

**Comment by SharpIceX** [comment]
请提供一下系统信息及`ping 127.0.0.1`的运行结果

**Comment by SharpIceX** [comment]
https://github.com/termux/termux-app/issues/3888
