### ISSUE TITLE
就是能不能给个拉出侧边栏的命令

### ISSUE THREAD

**Issue by Aberion** [hanxinhao000/ZeroTermux#56]
安卓11,lgg8x，骁龙855
![PicsArt_04-07-01 39 14](https://github.com/hanxinhao000/ZeroTermux/assets/65051091/4cfdbbb8-47b3-41f3-8d11-f1607dae0783)

**Comment by hanxinhao000** [comment]
左：
#!/data/data/com.termux/files/usr/bin/bash
am broadcast --user 0 \
                 --es com.termux.app.reload_style left \
                 -a com.termux.app.reload_style com.termux > /dev/null
右：
#!/data/data/com.termux/files/usr/bin/bash
am broadcast --user 0 \
		 --es com.termux.app.reload_style right \
		 -a com.termux.app.reload_style com.termux > /dev/null

**Comment by hanxinhao000** [comment]
看起来 ZT的命令似乎不知道什么原因没有写入到usr/bin 下个版本应该会修复
