### ISSUE TITLE
启动失败，报exec("/data/data/com.termux/files/usr/bin/login") ission denied

### ISSUE THREAD

**Issue by LarryFranken** [hanxinhao000/ZeroTermux#58]
![Screenshot_2024-04-27-20-14-06-072_com termux](https://github.com/hanxinhao000/ZeroTermux/assets/29144419/756a3e3a-fcbc-4b74-ac38-478108794141)
原生包安装失败提示已存在共享用户
![Screenshot_2024-04-27-19-22-37-220_io apkmody sai](https://github.com/hanxinhao000/ZeroTermux/assets/29144419/1bca595b-e5e4-468e-87a8-b7690dbe79ea)
**但是没有安装和扩展包**
![Screenshot_2024-04-27-20-23-43-625_com buak Link2SD](https://github.com/hanxinhao000/ZeroTermux/assets/29144419/21b0d94f-95da-44d0-86eb-512dfaef539a)

**Comment by SharpIceX** [comment]
请先参考以往的issues看看能不能解决

**Comment by LarryFranken** [comment]
卸载质感文件
