### ISSUE TITLE
移动云手机

### ISSUE THREAD

**Issue by hzjzqv2w3vwr4753** [hanxinhao000/ZeroTermux#61]
移动云手机中打开`ZeroTermux`，创建`QEMU` 虚拟机并启动，挂在后台，但是真机中划掉移动云手机后台，再次进入移动云手机，只能看到`ZeroTermux` 的终端，`QEMU`虚拟机终端被关闭，提示
```
qemu-system-x86_64: terminating
```
有人遇到嘛

**Comment by SharpIceX** [comment]
> 移动云手机中打开`ZeroTermux`，创建`QEMU` 虚拟机并启动，挂在后台，但是真机中划掉移动云手机后台，再次进入移动云手机，只能看到`ZeroTermux` 的终端，`QEMU`虚拟机终端被关闭，提示
> ```
> qemu-system-x86_64: terminating
> ```
> 有人遇到嘛

这应该是云手机问题吗，可能有某种用户离开就休眠的机制导致的。
