### ISSUE TITLE
请问如何启动zerotermux后自动启动Linux系统？

### ISSUE THREAD

**Issue by Jaderi666** [hanxinhao000/ZeroTermux#63]
通过zerotermux部署了Linux服务器，想做自动化，手机打开zerotermux后，自动执行启动Linux系统，自动启动Linux里的服务器，向大佬求助解决方案！谢谢

**Comment by hanxinhao000** [comment]
这个需要自己搜索下，或者让群友给你提供个恢复包

**Comment by fish4terrisa-MSDSM** [comment]
> 通过zerotermux部署了Linux服务器，想做自动化，手机打开zerotermux后，自动执行启动Linux系统，自动启动Linux里的服务器，向大佬求助解决方案！谢谢

可以写个脚本放到~/../usr/bin下，然后符号链接到~/../usr/bin/login 不过先用些好恢复的方法做准备(比如准备好那个可以读写zerotermux的文件管理器)
