### ISSUE TITLE
就不能换个签名吗，醉了 上来就要替换

### ISSUE THREAD

**Issue by 94zuocom** [hanxinhao000/ZeroTermux#65]

**Comment by FurryRbl** [comment]
看不懂你的问题。。。

**Comment by FurryRbl** [comment]
> > 看不懂你的问题。。。
> 
> 换个包名，和termux共存

做不到，也不可能做到。

**Comment by FurryRbl** [comment]
> > > > 看不懂你的问题。。。
> > > 
> > > 
> > > 更换包名，和termux共存
> > 
> > 做不到，也不可能做到。
> 
> 好吧，有些软件是基于termux的，就只能装一个， 不让动包名就很烦，

Termux本身的结构就不允许修改包名

**Comment by hanxinhao000** [comment]
可以用proot 替换包名，但是性能会很拉胯，之前考虑过，也做出来一个版本，实际体验下来很不好，proot 是拦截 IO操作流替换路径的，IO本来就很耗时，我自己用下来，性能大概损耗虽然不多，但是体验也很差
