### ISSUE TITLE
和原版操作有诸多冲突

### ISSUE THREAD

**Issue by yelong0951** [hanxinhao000/ZeroTermux#70]
我从termux原版转到zero，很多的操作不兼容，也不知道如何关闭。
例如，双指单击打开工具箱，和缩放手势冲突，希望可以添加一个改为 “双指双击” 的设置。
再如，音量键的操作，希望可以加个关闭的设置，个人想用到原版的音量键的功能。
我没在设置中找到关闭的选项，如果有关闭或是更改设置的方法请告诉我。谢谢

**Comment by hanxinhao000** [comment]
双指单击打开工具箱 可以在 ZeroTermux 设置当中关闭
路径 -> 左侧状态栏 -> 点击 ZeroTermux 文字标题 -> ZT设置 -> 禁止工具箱显示
音量键这个操作采纳了，下个版本会在设置当中加入 禁止音量+-处理左右状态栏

**Comment by hanxinhao000** [comment]
https://github.com/hanxinhao000/ZeroTermux/releases/download/release/ZeroTermux-0.118.1.41.apk
