### ISSUE TITLE
一个想法要补充

### ISSUE THREAD

**Issue by TDD788** [hanxinhao000/ZeroTermux#71]
您好，这只是一个想法，但非常有用，其中有一个零 termux 版本，它的插件完全在一个 apk 中，我们还可以添加一个选项，通过 u我们可以为应用程序提供更多语言的服务，我自己提供西班牙语

**Comment by SharpIceX** [comment]
> 您好，这只是一个想法，但非常有用，其中有一个零 termux 版本，它的插件完全在一个 apk 中，我们还可以添加一个选项，通过 u我们可以为应用程序提供更多语言的服务，我自己提供西班牙语

I don't understand your requirement. Could you please tell me your requirement in your native language or English?

**Comment by TDD788** [comment]
hola se podría usar weblate para agregar más idiomas al app de zero termux, yo ofrezco el español

**Comment by hanxinhao000** [comment]
你可以提供西班牙语到此页面，下个版本如果没什么问题则会加入此语言，并且在语言栏目会写入提供语言作者的名字

You can provide Spanish to this page. If there is no problem, the next version will add this language, and the name of the author who provided the language will be written in the language column.

Puede proporcionar español a esta página. Si no hay problemas, este idioma se agregará a la próxima versión y el nombre del autor que proporciona el idioma se escribirá en la columna de idioma.

**Comment by SharpIceX** [comment]
> 你可以提供西班牙语到此页面，下个版本如果没什么问题则会加入此语言，并且在语言栏目会写入提供语言作者的名字
> 
> You can provide Spanish to this page. If there is no problem, the next version will add this language, and the name of the author who provided the language will be written in the language column.
> 
> Puede proporcionar español a esta página. Si no hay problemas, este idioma se agregará a la próxima versión y el nombre del autor que proporciona el idioma se escribirá en la columna de idioma.

其实人家是想在weblate这类平台贡献翻译
