### ISSUE TITLE
这个win系统下载的被禁了

### ISSUE THREAD

**Issue by LiJiu-gfgfv** [hanxinhao000/ZeroTermux#72]
WIN下载跳转的百度网盘，但是百度网盘显示有违规内容
![Uploading Screenshot_2024-09-09-23-47-36-14_a252b927494330cdc2c8ba3b3f952e5e.jpg…]()

**Comment by SharpIceX** [comment]
什么被禁了

**Comment by LiJiu-gfgfv** [comment]
> 什么被禁了

下载win系统的网盘资源![Screenshot_2024-09-09-23-47-36-14_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/user-attachments/assets/516d07b5-9105-4c0c-a012-a16612d583a8)

**Comment by LiJiu-gfgfv** [comment]
> 什么被禁了

我是这个意思https://github.com/user-attachments/assets/b4dfecbe-27aa-445d-9a93-68fdf6fb51fd

**Comment by SharpIceX** [comment]
啊。。这个很早就被禁了

**Comment by LiJiu-gfgfv** [comment]
> 啊。。这个很早就被禁了

那咋整，从哪下

**Comment by hanxinhao000** [comment]
https://od.ixcmstudio.cn/repository/main/windows/

**Comment by hanxinhao000** [comment]
百度网盘的资源都平替到此网址了，你可以找找

**Comment by LiJiu-gfgfv** [comment]
> 百度网盘的资源都平替到此网址了，你可以找找

我想要win10可以吗

**Comment by LiJiu-gfgfv** [comment]
> > 百度网盘的资源都平替到此网址了，你可以找找
> 
> 我想要win10可以吗

看起来没有，那还是算了

**Comment by hanxinhao000** [comment]
https://od.ixcmstudio.cn/utermux/UTermux-Window%E8%99%9A%E6%8B%9F%E6%9C%BA/

**Comment by LiJiu-gfgfv** [comment]
> https://od.ixcmstudio.cn/utermux/UTermux-Window%E8%99%9A%E6%8B%9F%E6%9C%BA/

这到这里他不动了![Screenshot_2024-09-14-07-36-38-72_983ae72d68361e899dafc0e0f4aaab70.jpg](https://github.com/user-attachments/assets/3c9d392d-8965-40de-9e77-6e1887a841fa)

**Comment by hanxinhao000** [comment]
这镜像是从贴吧复制过来的，没有进行专门适配过，只能挨个往过试
