### ISSUE TITLE
一个需要我截屏发给开发者的报错，但他的QQ号好像是错的

### ISSUE THREAD

**Issue by LiJiu-gfgfv** [hanxinhao000/ZeroTermux#73]
![Screenshot_2024-09-14-09-36-20-94_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/c90f9970-13f8-4752-9f63-b70ec879a7fb)

**Comment by hanxinhao000** [comment]
好的

**Comment by hanxinhao000** [comment]
https://github.com/hanxinhao000/ZeroTermux/releases/download/release/ZeroTermux-0.118.1.41.apk

**Comment by LiJiu-gfgfv** [comment]
> https://github.com/hanxinhao000/ZeroTermux/releases/download/release/ZeroTermux-0.118.1.41.apk

装那个win10要等很久吗
