### ISSUE TITLE
关于许可证

### ISSUE THREAD

**Issue by sqhills** [hanxinhao000/ZeroTermux#8]
GNU GPL v3允许商用，请修改README
>When we speak of free software, we are referring to freedom, not price. Our General Public Licenses are designed to make sure that you have the freedom to distribute copies of free software (and charge for them if you wish), that you receive source code or can get it if you want it, that you can change the software or use pieces of it in new free programs, and that you know you can do these things.

参考[一](https://www.gnu.org/licenses/gpl-3.0.en.html)[二](https://www.ruanyifeng.com/blog/2021/09/weekly-issue-176.html)

**Comment by hanxinhao000** [comment]
GPL可以商用并且ZeroTermux也是开源软件，但是商用可能会出现很多责任纠纷，需要后续修改编译二次创作的作者承担一切后果和法律责任
